import type { SchedulerInfo } from '../types';

// Simplified YARN scheduler response for testing
export const mockSchedulerResponse = {
    scheduler: {
        schedulerInfo: {
            type: 'capacityScheduler',
            queueName: 'root',
            queuePath: 'root',
            queueType: 'parent',
            queuePriority: 0,
            capacity: 100.0,
            usedCapacity: 60.0,
            maxCapacity: 100.0,
            absoluteCapacity: 100.0,
            absoluteMaxCapacity: 100.0,
            absoluteUsedCapacity: 60.0,
            numApplications: 8,
            numActiveApplications: 5,
            numPendingApplications: 3,
            resourcesUsed: { memory: 32768, vCores: 16 },
            state: 'RUNNING',
            autoCreationEligibility: 'off',
            queues: {
                queue: [
                    {
                        type: 'capacitySchedulerLeafQueueInfo',
                        queueName: 'default',
                        queuePath: 'root.default',
                        queueType: 'leaf',
                        queuePriority: 0,
                        capacity: 10.0,
                        usedCapacity: 21.1,
                        maxCapacity: 100.0,
                        absoluteCapacity: 10.0,
                        absoluteMaxCapacity: 100.0,
                        absoluteUsedCapacity: 2.1,
                        numApplications: 1,
                        numActiveApplications: 1,
                        numPendingApplications: 0,
                        resourcesUsed: { memory: 1024, vCores: 1 },
                        state: 'RUNNING',
                        autoCreationEligibility: 'off',
                    },
                    {
                        type: 'capacityScheduler',
                        queueName: 'production',
                        queuePath: 'root.production',
                        queueType: 'parent',
                        queuePriority: 0,
                        capacity: 70.0,
                        usedCapacity: 45.7,
                        maxCapacity: 100.0,
                        absoluteCapacity: 70.0,
                        absoluteMaxCapacity: 100.0,
                        absoluteUsedCapacity: 32.0,
                        numApplications: 5,
                        numActiveApplications: 3,
                        numPendingApplications: 2,
                        resourcesUsed: { memory: 20480, vCores: 10 },
                        state: 'RUNNING',
                        autoCreationEligibility: 'off',
                        queues: {
                            queue: [
                                {
                                    type: 'capacitySchedulerLeafQueueInfo',
                                    queueName: 'batch',
                                    queuePath: 'root.production.batch',
                                    queueType: 'leaf',
                                    queuePriority: 0,
                                    capacity: 60.0,
                                    usedCapacity: 50.0,
                                    maxCapacity: 100.0,
                                    absoluteCapacity: 42.0,
                                    absoluteMaxCapacity: 70.0,
                                    absoluteUsedCapacity: 21.0,
                                    numApplications: 3,
                                    numActiveApplications: 2,
                                    numPendingApplications: 1,
                                    resourcesUsed: { memory: 12288, vCores: 6 },
                                    state: 'RUNNING',
                                    autoCreationEligibility: 'off',
                                },
                                {
                                    type: 'capacitySchedulerLeafQueueInfo',
                                    queueName: 'interactive',
                                    queuePath: 'root.production.interactive',
                                    queueType: 'leaf',
                                    queuePriority: 0,
                                    capacity: 40.0,
                                    usedCapacity: 25.0,
                                    maxCapacity: 100.0,
                                    absoluteCapacity: 28.0,
                                    absoluteMaxCapacity: 70.0,
                                    absoluteUsedCapacity: 7.0,
                                    numApplications: 2,
                                    numActiveApplications: 1,
                                    numPendingApplications: 1,
                                    resourcesUsed: { memory: 8192, vCores: 4 },
                                    state: 'RUNNING',
                                    autoCreationEligibility: 'off',
                                },
                            ],
                        },
                    },
                    {
                        type: 'capacityScheduler',
                        queueName: 'development',
                        queuePath: 'root.development',
                        queueType: 'parent',
                        queuePriority: 0,
                        capacity: 20.0,
                        usedCapacity: 60.0,
                        maxCapacity: 50.0,
                        absoluteCapacity: 20.0,
                        absoluteMaxCapacity: 50.0,
                        absoluteUsedCapacity: 12.0,
                        numApplications: 2,
                        numActiveApplications: 1,
                        numPendingApplications: 1,
                        resourcesUsed: { memory: 11264, vCores: 5 },
                        state: 'RUNNING',
                        autoCreationEligibility: 'off',
                        queues: {
                            queue: [
                                {
                                    type: 'capacitySchedulerLeafQueueInfo',
                                    queueName: 'team1',
                                    queuePath: 'root.development.team1',
                                    queueType: 'leaf',
                                    queuePriority: 0,
                                    capacity: 60.0,
                                    usedCapacity: 75.0,
                                    maxCapacity: 100.0,
                                    absoluteCapacity: 12.0,
                                    absoluteMaxCapacity: 20.0,
                                    absoluteUsedCapacity: 9.0,
                                    numApplications: 1,
                                    numActiveApplications: 1,
                                    numPendingApplications: 0,
                                    resourcesUsed: { memory: 8192, vCores: 4 },
                                    state: 'RUNNING',
                                    autoCreationEligibility: 'off',
                                },
                                {
                                    type: 'capacitySchedulerLeafQueueInfo',
                                    queueName: 'team2',
                                    queuePath: 'root.development.team2',
                                    queueType: 'leaf',
                                    queuePriority: 0,
                                    capacity: 40.0,
                                    usedCapacity: 37.5,
                                    maxCapacity: 80.0,
                                    absoluteCapacity: 8.0,
                                    absoluteMaxCapacity: 16.0,
                                    absoluteUsedCapacity: 3.0,
                                    numApplications: 1,
                                    numActiveApplications: 0,
                                    numPendingApplications: 1,
                                    resourcesUsed: { memory: 3072, vCores: 1 },
                                    state: 'RUNNING',
                                    autoCreationEligibility: 'off',
                                },
                            ],
                        },
                    },
                ],
            },
        } as SchedulerInfo,
    },
};

// Additional mock data for testing
export const mockConfigResponse = {
    property: [
        { name: 'yarn.scheduler.capacity.root.queues', value: 'default,production,development' },
        { name: 'yarn.scheduler.capacity.root.default.capacity', value: '10' },
        { name: 'yarn.scheduler.capacity.root.default.maximum-capacity', value: '100' },
        { name: 'yarn.scheduler.capacity.root.production.capacity', value: '70' },
        { name: 'yarn.scheduler.capacity.root.production.maximum-capacity', value: '100' },
        { name: 'yarn.scheduler.capacity.root.production.queues', value: 'batch,interactive' },
        { name: 'yarn.scheduler.capacity.root.production.batch.capacity', value: '60' },
        { name: 'yarn.scheduler.capacity.root.production.batch.maximum-capacity', value: '100' },
        { name: 'yarn.scheduler.capacity.root.production.interactive.capacity', value: '40' },
        { name: 'yarn.scheduler.capacity.root.production.interactive.maximum-capacity', value: '100' },
        { name: 'yarn.scheduler.capacity.root.development.capacity', value: '20' },
        { name: 'yarn.scheduler.capacity.root.development.maximum-capacity', value: '50' },
        { name: 'yarn.scheduler.capacity.root.development.queues', value: 'team1,team2' },
        { name: 'yarn.scheduler.capacity.root.development.team1.capacity', value: '60' },
        { name: 'yarn.scheduler.capacity.root.development.team1.maximum-capacity', value: '100' },
        { name: 'yarn.scheduler.capacity.root.development.team2.capacity', value: '40' },
        { name: 'yarn.scheduler.capacity.root.development.team2.maximum-capacity', value: '80' },
        { name: 'yarn.scheduler.capacity.maximum-applications', value: '10000' },
        { name: 'yarn.scheduler.capacity.resource-calculator', value: 'org.apache.hadoop.yarn.util.resource.DefaultResourceCalculator' },
    ],
};

export const mockNodeLabelsResponse = {
    nodeLabelsInfo: {
        nodeLabelInfo: [
            { name: 'gpu', exclusivity: true },
            { name: 'ssd', exclusivity: false },
            { name: 'highmem', exclusivity: true },
        ],
    },
};

export const mockVersionResponse = {
    versionID: 1234567890,
};