import type { SchedulerInfoField } from './types';

export const SCHEDULER_INFO_METADATA: Record<string, SchedulerInfoField> = {
  queueName: { displayName: 'Queue Name' },
  queuePath: { displayName: 'Queue Path' },
  state: { displayName: 'State' },
  type: { displayName: 'Queue Type' },
  capacity: { displayName: 'Effective Capacity', unit: '%' },
  usedCapacity: { displayName: 'Used Capacity', unit: '%' },
  maxCapacity: { displayName: 'Effective Max Capacity', unit: '%' },
  absoluteCapacity: { displayName: 'Absolute Capacity', unit: '%' },
  absoluteMaxCapacity: { displayName: 'Absolute Max Capacity', unit: '%' },
  absoluteUsedCapacity: { displayName: 'Absolute Used Capacity', unit: '%' },
  numApplications: { displayName: 'Total Applications' },
  maxParallelApps: { displayName: 'Max Parallel Apps' },
  resourcesUsed: {
    displayName: 'Resources Used',
    memory: { displayName: 'Memory Used', unit: 'MB' },
    vCores: { displayName: 'VCores Used' },
  },
  mode: { displayName: 'Capacity Mode' },
  weight: { displayName: 'Weight' },
  normalizedWeight: { displayName: 'Normalized Weight' },
  numActiveApplications: { displayName: 'Active Applications' },
  numPendingApplications: { displayName: 'Pending Applications' },
  numContainers: { displayName: 'Total Containers' },
  allocatedContainers: { displayName: 'Allocated Containers' },
  reservedContainers: { displayName: 'Reserved Containers' },
  pendingContainers: { displayName: 'Pending Containers' },
  maxApplications: { displayName: 'Max Applications (Queue Limit)' },
  userLimitFactor: { displayName: 'User Limit Factor' },
  defaultPartitionEffectiveMinResource: {
    displayName: 'Default Partition Effective Min Resource',
    memory: { displayName: 'Memory', unit: 'MB' },
    vCores: { displayName: 'VCores' },
  },
  defaultPartitionEffectiveMaxResource: {
    displayName: 'Default Partition Effective Max Resource',
    memory: { displayName: 'Memory', unit: 'MB' },
    vCores: { displayName: 'VCores' },
  },
};