/**
 * Error codes for better error handling
 */
export const ERROR_CODES = {
  LOAD_INITIAL_DATA_FAILED: 'LOAD_INITIAL_DATA_FAILED',
  REFRESH_SCHEDULER_FAILED: 'REFRESH_SCHEDULER_FAILED',
  APPLY_CHANGES_FAILED: 'APPLY_CHANGES_FAILED',
  INVALID_QUEUE_PATH: 'INVALID_QUEUE_PATH',
  INVALID_PROPERTY_NAME: 'INVALID_PROPERTY_NAME',
  INVALID_PROPERTY_VALUE: 'INVALID_PROPERTY_VALUE',
  INVALID_QUEUE_NAME: 'INVALID_QUEUE_NAME',
  EMPTY_STAGED_CHANGES: 'EMPTY_STAGED_CHANGES',
  API_ERROR: 'API_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ADD_NODE_LABEL_FAILED: 'ADD_NODE_LABEL_FAILED',
  REMOVE_NODE_LABEL_FAILED: 'REMOVE_NODE_LABEL_FAILED',
  ASSIGN_NODE_TO_LABEL_FAILED: 'ASSIGN_NODE_TO_LABEL_FAILED',
  QUEUE_ALREADY_EXISTS: 'QUEUE_ALREADY_EXISTS',
  MUTATION_BLOCKED: 'MUTATION_BLOCKED',
} as const;
