/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutNodeLabelsRouteImport } from './routes/_layout/node-labels'
import { Route as LayoutGlobalSettingsRouteImport } from './routes/_layout/global-settings'
import { Route as LayoutQueueQueuePathRouteImport } from './routes/_layout/queue.$queuePath'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNodeLabelsRoute = LayoutNodeLabelsRouteImport.update({
  id: '/node-labels',
  path: '/node-labels',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGlobalSettingsRoute = LayoutGlobalSettingsRouteImport.update({
  id: '/global-settings',
  path: '/global-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQueueQueuePathRoute = LayoutQueueQueuePathRouteImport.update({
  id: '/queue/$queuePath',
  path: '/queue/$queuePath',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/global-settings': typeof LayoutGlobalSettingsRoute
  '/node-labels': typeof LayoutNodeLabelsRoute
  '/': typeof LayoutIndexRoute
  '/queue/$queuePath': typeof LayoutQueueQueuePathRoute
}
export interface FileRoutesByTo {
  '/global-settings': typeof LayoutGlobalSettingsRoute
  '/node-labels': typeof LayoutNodeLabelsRoute
  '/': typeof LayoutIndexRoute
  '/queue/$queuePath': typeof LayoutQueueQueuePathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/global-settings': typeof LayoutGlobalSettingsRoute
  '/_layout/node-labels': typeof LayoutNodeLabelsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/queue/$queuePath': typeof LayoutQueueQueuePathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/global-settings' | '/node-labels' | '/' | '/queue/$queuePath'
  fileRoutesByTo: FileRoutesByTo
  to: '/global-settings' | '/node-labels' | '/' | '/queue/$queuePath'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/global-settings'
    | '/_layout/node-labels'
    | '/_layout/'
    | '/_layout/queue/$queuePath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/node-labels': {
      id: '/_layout/node-labels'
      path: '/node-labels'
      fullPath: '/node-labels'
      preLoaderRoute: typeof LayoutNodeLabelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/global-settings': {
      id: '/_layout/global-settings'
      path: '/global-settings'
      fullPath: '/global-settings'
      preLoaderRoute: typeof LayoutGlobalSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/queue/$queuePath': {
      id: '/_layout/queue/$queuePath'
      path: '/queue/$queuePath'
      fullPath: '/queue/$queuePath'
      preLoaderRoute: typeof LayoutQueueQueuePathRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutGlobalSettingsRoute: typeof LayoutGlobalSettingsRoute
  LayoutNodeLabelsRoute: typeof LayoutNodeLabelsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutQueueQueuePathRoute: typeof LayoutQueueQueuePathRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutGlobalSettingsRoute: LayoutGlobalSettingsRoute,
  LayoutNodeLabelsRoute: LayoutNodeLabelsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutQueueQueuePathRoute: LayoutQueueQueuePathRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
