/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NodeLabelsRouteImport } from './routes/node-labels'
import { Route as GlobalSettingsRouteImport } from './routes/global-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueQueuePathRouteImport } from './routes/queue.$queuePath'

const NodeLabelsRoute = NodeLabelsRouteImport.update({
  id: '/node-labels',
  path: '/node-labels',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalSettingsRoute = GlobalSettingsRouteImport.update({
  id: '/global-settings',
  path: '/global-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueQueuePathRoute = QueueQueuePathRouteImport.update({
  id: '/queue/$queuePath',
  path: '/queue/$queuePath',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/global-settings': typeof GlobalSettingsRoute
  '/node-labels': typeof NodeLabelsRoute
  '/queue/$queuePath': typeof QueueQueuePathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/global-settings': typeof GlobalSettingsRoute
  '/node-labels': typeof NodeLabelsRoute
  '/queue/$queuePath': typeof QueueQueuePathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/global-settings': typeof GlobalSettingsRoute
  '/node-labels': typeof NodeLabelsRoute
  '/queue/$queuePath': typeof QueueQueuePathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/global-settings' | '/node-labels' | '/queue/$queuePath'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/global-settings' | '/node-labels' | '/queue/$queuePath'
  id:
    | '__root__'
    | '/'
    | '/global-settings'
    | '/node-labels'
    | '/queue/$queuePath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlobalSettingsRoute: typeof GlobalSettingsRoute
  NodeLabelsRoute: typeof NodeLabelsRoute
  QueueQueuePathRoute: typeof QueueQueuePathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/node-labels': {
      id: '/node-labels'
      path: '/node-labels'
      fullPath: '/node-labels'
      preLoaderRoute: typeof NodeLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-settings': {
      id: '/global-settings'
      path: '/global-settings'
      fullPath: '/global-settings'
      preLoaderRoute: typeof GlobalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$queuePath': {
      id: '/queue/$queuePath'
      path: '/queue/$queuePath'
      fullPath: '/queue/$queuePath'
      preLoaderRoute: typeof QueueQueuePathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlobalSettingsRoute: GlobalSettingsRoute,
  NodeLabelsRoute: NodeLabelsRoute,
  QueueQueuePathRoute: QueueQueuePathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
